export const SET_USER_STATUS = 'SET_USER_STATUS';
export const SET_USER_STATUS_SUCCESS = 'SET_USER_STATUS_SUCCESS';
export const SET_USER_STATUS_FAILURE = 'SET_USER_STATUS_FAILURE';

export const SET_LOCATION = 'SET_LOCATION';
export const SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS';
export const SET_LOCATION_FAILURE = 'SET_LOCATION_FAILURE';

export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN';
export const SET_DEVICE_TOKEN_SUCCESS = 'SET_DEVICE_TOKEN_SUCCESS';
export const SET_DEVICE_TOKEN_FAILURE = 'SET_DEVICE_TOKEN_FAILURE';

export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';
export const SET_CURRENT_SCREEN_SUCCESS = 'SET_CURRENT_SCREEN_SUCCESS';
export const SET_CURRENT_SCREEN_FAILURE = 'SET_CURRENT_SCREEN_FAILURE';


export const SET_ONESIGNAL_ID = 'SET_ONESIGNAL_ID';

export const ADD_ADDRESS_HISTORY = 'Add_ADDRESS_HISTORY';
export const REMOVE_ADDRESS_HISTORY = 'REMOVE_ADDRESS_HISTORY';
export const INIT_ADDRESS_HISTORY = 'INIT_ADDRESS_HISTORY';

export const SET_TERMS_AGREE = 'SET_TERMS_AGREE';

export const SET_CLICK_AREA = 'SET_CLICK_AREA';

export const SET_ENTER_HOME = 'SET_ENTER_HOME';

export const SET_TAB_SCROLL_LOCK = 'SET_TAB_SCROLL_LOCK';

export const SET_DEFAULT_VALUE_CONFIG = 'SET_DEFAULT_VALUE_CONFIG';


