export const FIND_ID_ADDRESS = 'FIND_ID_ADDRESS';
export const FIND_ID_ADDRESS_SUCCESS = 'FIND_ID_ADDRESS_SUCCESS';
export const FIND_ID_ADDRESS_FAILURE = 'FIND_ID_ADDRESS_FAILURE';

export const FIND_ID_PHONE = 'FIND_ID_PHONE';
export const FIND_ID_PHONE_SUCCESS = 'FIND_ID_PHONE_SUCCESS';
export const FIND_ID_PHONE_FAILURE = 'FIND_ID_PHONE_FAILURE';

export const FIND_ID_EMAIL = 'FIND_ID_EMAIL';
export const FIND_ID_EMAIL_SUCCESS = 'FIND_ID_EMAIL_SUCCESS';
export const FIND_ID_EMAIL_FAILURE = 'FIND_ID_EMAIL_FAILURE';

export const CHANGE_SELLER_ID = 'CHANGE_SELLER_ID';
export const CHANGE_SELLER_ID_SUCCESS = 'CHANGE_SELLER_ID_SUCCESS';
export const CHANGE_SELLER_ID_FAILURE = 'CHANGE_SELLER_ID_FAILURE';

export const CHANGE_SELLER_PASSWORD = 'CHANGE_SELLER_PASSWORD';
export const CHANGE_SELLER_PASSWORD_SUCCESS = 'CHANGE_SELLER_PASSWORD_SUCCESS';
export const CHANGE_SELLER_PASSWORD_FAILURE = 'CHANGE_SELLER_PASSWORD_FAILURE';

export const CHANGE_SHOP_ADDRESS = 'CHANGE_SHOP_ADDRESS';
export const CHANGE_SHOP_ADDRESS_SUCCESS = 'CHANGE_SHOP_ADDRESS_SUCCESS';
export const CHANGE_SHOP_ADDRESS_FAILURE = 'CHANGE_SHOP_ADDRESS_FAILURE';

export const FIND_PASSWORD_PHONE = 'FIND_PASSWORD_PHONE';
export const FIND_PASSWORD_PHONE_SUCCESS = 'FIND_PASSWORD_PHONE_SUCCESS';
export const FIND_PASSWORD_PHONE_FAILURE = 'FIND_PASSWORD_PHONE_FAILURE';

export const FIND_PASSWORD_EMAIL = 'FIND_PASSWORD_EMAIL';
export const FIND_PASSWORD_EMAIL_SUCCESS = 'FIND_PASSWORD_EMAIL_SUCCESS';
export const FIND_PASSWORD_EMAIL_FAILURE = 'FIND_PASSWORD_EMAIL_FAILURE';

export const SET_DEFAULT_VALUE_FIND_INFO = 'SET_DEFAULT_VALUE_FIND_INFO';
