export const GET_BANNER_TEXT = 'GET_BANNER_TEXT';
export const GET_BANNER_TEXT_SUCCESS = 'GET_BANNER_TEXT_SUCCESS';
export const GET_BANNER_TEXT_FAILURE = 'GET_BANNER_TEXT_FAILURE';

export const SET_DEFAULT_VALUE_BANNER = 'SET_DEFAULT_VALUE_BANNER';
