export const GET_NOTICE = 'GET_NOTICE';
export const GET_NOTICE_SUCCESS = 'GET_NOTICE_SUCCESS';
export const GET_NOTICE_FAILURE = 'GET_NOTICE_FAILURE';

export const SET_DEFAULT_VALUE_NOTICE = 'SET_DEFAULT_VALUE_NOTICE';
