export const GET_CEO_REPORT = 'GET_CEO_REPORT';
export const GET_CEO_REPORT_SUCCESS = 'GET_CEO_REPORT_SUCCESS';
export const GET_CEO_REPORT_FAILURE = 'GET_CEO_REPORT_FAILURE';

export const UPDATE_CEO_REPORT = 'UPDATE_CEO_REPORT';
export const UPDATE_CEO_REPORT_SUCCESS = 'UPDATE_CEO_REPORT_SUCCESS';
export const UPDATE_CEO_REPORT_FAILURE = 'UPDATE_CEO_REPORT_FAILURE';

export const DELETE_CEO_REPORT = 'DELETE_CEO_REPORT';
export const DELETE_CEO_REPORT_SUCCESS = 'DELETE_CEO_REPORT_SUCCESS';
export const DELETE_CEO_REPORT_FAILURE = 'DELETE_CEO_REPORT_FAILURE';

export const REPLY_CEO_REPORT = 'REPLY_CEO_REPORT';
export const REPLY_CEO_REPORT_SUCCESS = 'REPLY_CEO_REPORT_SUCCESS';
export const REPLY_CEO_REPORT_FAILURE = 'REPLY_CEO_REPORT_FAILURE';

export const UPDATE_REPLY_BY_CEO = 'UPDATE_REPLY_BY_CEO';
export const UPDATE_REPLY_BY_CEO_SUCCESS = 'UPDATE_REPLY_BY_CEO_SUCCESS';
export const UPDATE_REPLY_BY_CEO_FAILURE = 'UPDATE_REPLY_BY_CEO_FAILURE';

export const DELETE_REPLY_BY_CEO = 'DELETE_REPLY_BY_CEO';
export const DELETE_REPLY_BY_CEO_SUCCESS = 'DELETE_REPLY_BY_CEO_SUCCESS';
export const DELETE_REPLY_BY_CEO_FAILURE = 'DELETE_REPLY_BY_CEO_FAILURE';

export const REPORT_HOPE_TO_CEO = 'REPORT_HOPE_TO_CEO';
export const REPORT_HOPE_TO_CEO_SUCCESS = 'REPORT_HOPE_TO_CEO_SUCCESS';
export const REPORT_HOPE_TO_CEO_FAILURE = 'REPORT_HOPE_TO_CEO_FAILURE';

export const REPORT_HOPE_TO_CEO_BY_CUSTOMER = 'REPORT_HOPE_TO_CEO_BY_CUSTOMER';
export const REPORT_HOPE_TO_CEO_BY_CUSTOMER_SUCCESS = 'REPORT_HOPE_TO_CEO_BY_CUSTOMER_SUCCESS';
export const REPORT_HOPE_TO_CEO_BY_CUSTOMER_FAILURE = 'REPORT_HOPE_TO_CEO_BY_CUSTOMER_FAILURE';

export const SET_DEFAULT_VALUE_CEO_REPORT = 'SET_DEFAULT_VALUE_CEO_REPORT';
