export const SET_MY_NOTIFICATION = "SET_MY_NOTIFICATION";

export const SET_IS_READ_MY_NOTIFICATION = "SET_IS_READ_MY_NOTIFICATION";


export const SET_DEFAULT_VALUE_MY_NOTIFICATION = "SET_DEFAULT_VALUE_MY_NOTIFICATION";
