import {SET_DEFAULT_VALUE_MY_NOTIFICATION} from "../MyNotification/types";

export const GET_NEWS_EVENTS = 'GET_NEWS_EVENTS';
export const GET_NEWS_EVENTS_SUCCESS = 'GET_NEWS_EVENTS_SUCCESS';
export const GET_NEWS_EVENTS_FAILURE = 'GET_NEWS_EVENTS_FAILURE';

export const GET_FAVORITE_NEWS_EVENTS = 'GET_FAVORITE_NEWS_EVENTS';
export const GET_FAVORITE_NEWS_EVENTS_SUCCESS = 'GET_FAVORITE_NEWS_EVENTS_SUCCESS';
export const GET_FAVORITE_NEWS_EVENTS_FAILURE = 'GET_FAVORITE_NEWS_EVENTS_FAILURE';

export const UPDATE_SHOP_INFO = 'UPDATE_SHOP_INFO';
export const UPDATE_SHOP_INFO_SUCCESS = 'UPDATE_SHOP_INFO_SUCCESS';
export const UPDATE_SHOP_INFO_FAILURE = 'UPDATE_SHOP_INFO_FAILURE';

export const REGISTER_SHOP_INFO = 'REGISTER_SHOP_INFO';
export const REGISTER_SHOP_INFO_SUCCESS = 'REGISTER_SHOP_INFO_SUCCESS';
export const REGISTER_SHOP_INFO_FAILURE = 'REGISTER_SHOP_INFO_FAILURE';

export const UPDATE_MARK_IMAGE = "UPDATE_MARK_IMAGE";
export const UPDATE_MARK_IMAGE_SUCCESS = "UPDATE_MARK_IMAGE_SUCCESS";
export const UPDATE_MARK_IMAGE_FAILURE = "UPDATE_MARK_IMAGE_FAILURE";

export const SET_DEFAULT_VALUE_HOME = "SET_DEFAULT_VALUE_HOME";

export const UPDATE_NEWSEVNET_REPLY_CNT = 'UPDATE_NEWSEVNET_REPLY_CNT';
export const UPDATE_FAVORITE_NEWSEVNET_REPLY_CNT = 'UPDATE_FAVORITE_NEWSEVNET_REPLY_CNT';

export const SET_IS_LOADING_NEWS_EVENTS = 'SET_IS_LOADING_NEWS_EVENTS';

export const UPDATE_FAVORITE_NEWSEVNET_FAVORITE = 'UPDATE_FAVORITE_NEWSEVNET_FAVORITE';
export const UPDATE_NEWSEVNET_FAVORITE = 'UPDATE_NEWSEVNET_FAVORITE';
