require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'mymarketplaceapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'NMapsMap'

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'mymarketplaceappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
