export const GET_SHOP_INFO = 'GET_SHOP_INFO';
export const GET_SHOP_INFO_SUCCESS = 'GET_SHOP_INFO_SUCCESS';
export const GET_SHOP_INFO_FAILURE = 'GET_SHOP_INFO_FAILURE';

export const GET_BUSINESS_CATEGORY = 'GET_BUSINESS_CATEGORY';
export const GET_BUSINESS_CATEGORY_SUCCESS = 'GET_BUSINESS_CATEGORY_SUCCESS';
export const GET_BUSINESS_CATEGORY_FAILURE = 'GET_BUSINESS_CATEGORY_FAILURE';

export const UPDATE_SHOP_INFO = 'UPDATE_SHOP_INFO';
export const UPDATE_SHOP_INFO_SUCCESS = 'UPDATE_SHOP_INFO_SUCCESS';
export const UPDATE_SHOP_INFO_FAILURE = 'UPDATE_SHOP_INFO_FAILURE';

export const REGISTER_SHOP_INFO = 'REGISTER_SHOP_INFO';
export const REGISTER_SHOP_INFO_SUCCESS = 'REGISTER_SHOP_INFO_SUCCESS';
export const REGISTER_SHOP_INFO_FAILURE = 'REGISTER_SHOP_INFO_FAILURE';

export const UPDATE_MARK_IMAGE = "UPDATE_MARK_IMAGE";
export const UPDATE_MARK_IMAGE_SUCCESS = "UPDATE_MARK_IMAGE_SUCCESS";
export const UPDATE_MARK_IMAGE_FAILURE = "UPDATE_MARK_IMAGE_FAILURE";

export const REPORT_TO_CEO = "REPORT_TO_CEO";
export const REPORT_TO_CEO_SUCCESS = "REPORT_TO_CEO_SUCCESS";
export const REPORT_TO_CEO_FAILURE = "REPORT_TO_CEO_FAILURE";

export const GET_SHOP_INFO_BY_SHOPID = 'GET_SHOP_INFO_BY_SHOPID';
export const GET_SHOP_INFO_BY_SHOPID_SUCCESS = 'GET_SHOP_INFO_BY_SHOPID_SUCCESS';
export const GET_SHOP_INFO_BY_SHOPID_FAILURE = 'GET_SHOP_INFO_BY_SHOPID_FAILURE';

export const UPDATE_BUSINESS_INFO = 'UPDATE_BUSINESS_INFO';
export const UPDATE_BUSINESS_INFO_SUCCESS = 'UPDATE_BUSINESS_INFO_SUCCESS';
export const UPDATE_BUSINESS_INFO_FAILURE = 'UPDATE_BUSINESS_INFO_FAILURE';

export const SET_DEFAULT_VALUE_SHOP = 'SET_DEFAULT_VALUE_SHOP';

export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';

export const UPDATE_PHONE_VERIFICATION = 'UPDATE_PHONE_VERIFICATION';
export const UPDATE_PHONE_VERIFICATION_SUCCESS = 'UPDATE_PHONE_VERIFICATION_SUCCESS';
export const UPDATE_PHONE_VERIFICATION_FAILURE = 'UPDATE_PHONE_VERIFICATION_FAILURE';

export const UPDATE_EMAIL_VERIFICATION = 'UPDATE_EMAIL_VERIFICATION';
export const UPDATE_EMAIL_VERIFICATION_SUCCESS = 'UPDATE_EMAIL_VERIFICATION_SUCCESS';
export const UPDATE_EMAIL_VERIFICATION_FAILURE = 'UPDATE_EMAIL_VERIFICATION_FAILURE';
