export const GET_NEWSEVENT_CATEGORY = 'GET_NEWSEVENT_CATEGORY';
export const GET_NEWSEVENT_CATEGORY_SUCCESS = 'GET_NEWSEVENT_CATEGORY_SUCCESS';
export const GET_NEWSEVENT_CATEGORY_FAILURE = 'GET_NEWSEVENT_CATEGORY_FAILURE';

export const REGISTER_NEWSEVENT = 'REGISTER_NEWSEVENT';
export const REGISTER_NEWSEVENT_SUCCESS = 'REGISTER_NEWSEVENT_SUCCESS';
export const REGISTER_NEWSEVENT_FAILURE = 'REGISTER_NEWSEVENT_FAILURE';

export const UPDATE_NEWSEVENT = 'UPDATE_NEWSEVENT';
export const UPDATE_NEWSEVENT_SUCCESS = 'UPDATE_NEWSEVENT_SUCCESS';
export const UPDATE_NEWSEVENT_FAILURE = 'UPDATE_NEWSEVENT_FAILURE';

export const GET_NEWSEVENT = 'GET_NEWSEVENT';
export const GET_NEWSEVENT_SUCCESS = 'GET_NEWSEVENT_SUCCESS';
export const GET_NEWSEVENT_FAILURE = 'GET_NEWSEVENT_FAILURE';

export const DELETE_NEWSEVENT = 'DELETE_NEWSEVENT';
export const DELETE_NEWSEVENT_SUCCESS = 'DELETE_NEWSEVENT_SUCCESS';
export const DELETE_NEWSEVENT_FAILURE = 'DELETE_NEWSEVENT_FAILURE';

export const REPORT_TO_NEWSEVENT_COMMENT = 'REPORT_TO_NEWSEVENT_COMMENT';
export const REPORT_TO_NEWSEVENT_COMMENT_SUCCESS = 'REPORT_TO_NEWSEVENT_COMMENT_SUCCESS';
export const REPORT_TO_NEWSEVENT_COMMENT_FAILURE = 'REPORT_TO_NEWSEVENT_COMMENT_FAILURE';

export const REPORT_TO_NEWSEVENT = 'REPORT_TO_NEWSEVENT';
export const REPORT_TO_NEWSEVENT_SUCCESS = 'REPORT_TO_NEWSEVENT_SUCCESS';
export const REPORT_TO_NEWSEVENT_FAILURE = 'REPORT_TO_NEWSEVENT_FAILURE';

export const SEND_COMMENT_TO_NEWSEVENT = 'SEND_COMMENT_TO_NEWSEVENT';
export const SEND_COMMENT_TO_NEWSEVENT_SUCCESS = 'SEND_COMMENT_TO_NEWSEVENT_SUCCESS';
export const SEND_COMMENT_TO_NEWSEVENT_FAILURE = 'SEND_COMMENT_TO_NEWSEVENT_FAILURE';

export const SET_IS_COMMENT_LOADING = 'SET_IS_COMMENT_LOADING';

export const SET_DEFAULT_VALUE_NEWSEVNET = 'SET_DEFAULT_VALUE_NEWSEVNET';

export const UPDATE_SHOP_NEWSEVNET_REPLY_CNT = 'UPDATE_SHOP_NEWSEVNET_REPLY_CNT';





