export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';
export const LOGIN_CUSTOMER_SUCCESS = 'LOGIN_CUSTOMER_SUCCESS';
export const LOGIN_CUSTOMER_FAILURE = 'LOGIN_CUSTOMER_FAILURE';

export const REGISTER_CUSTOMER_ONESIGNALID = 'REGISTER_CUSTOMER_ONESIGNALID';
export const REGISTER_CUSTOMER_ONESIGNALID_SUCCESS = 'REGISTER_CUSTOMER_ONESIGNALID_SUCCESS';
export const REGISTER_CUSTOMER_ONESIGNALID_FAILURE = 'REGISTER_CUSTOMER_ONESIGNALID_FAILURE';

export const SET_CUSTOMER_AUTH = 'SET_CUSTOMER_AUTH';

export const SET_DEFAULT_VALUE_CUSTOMER_AUTH = 'SET_DEFAULT_VALUE_CUSTOMER_AUTH';
