export const SET_CEO_NOTIFICATION = "SET_CEO_NOTIFICATION";

export const SET_IS_READ_CEO_NOTIFICATION = "SET_IS_READ_CEO_NOTIFICATION";

export const SET_DEFAULT_VALUE_CEO_NOTIFICATION = "SET_DEFAULT_VALUE_CEO_NOTIFICATION";
